// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZFK6n7A5Py1JcXKuHYghg-f9zIIS-B8c',
    appId: '1:820367744835:web:c6fcb18d3e5baf320419f6',
    messagingSenderId: '820367744835',
    projectId: 'smart-traffic-frontend',
    authDomain: 'smart-traffic-frontend.firebaseapp.com',
    storageBucket: 'smart-traffic-frontend.firebasestorage.app',
    measurementId: 'G-605F1PTPFT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcVK-IFyqIG2RcNJ-5wmC9akcGdduhZDw',
    appId: '1:820367744835:android:8e2cb1be386c99220419f6',
    messagingSenderId: '820367744835',
    projectId: 'smart-traffic-frontend',
    storageBucket: 'smart-traffic-frontend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP1ywM5qnJY3IAzL4BwZNN70RM8ojFUoM',
    appId: '1:820367744835:ios:ccc436b91da0b1ed0419f6',
    messagingSenderId: '820367744835',
    projectId: 'smart-traffic-frontend',
    storageBucket: 'smart-traffic-frontend.firebasestorage.app',
    androidClientId: '820367744835-o240i46k2mfhccphrvo7bs85gcjsngkm.apps.googleusercontent.com',
    iosClientId: '820367744835-90urleu57pcjjm5sesl109p9k6k6chhj.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartTrafficFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCP1ywM5qnJY3IAzL4BwZNN70RM8ojFUoM',
    appId: '1:820367744835:ios:ccc436b91da0b1ed0419f6',
    messagingSenderId: '820367744835',
    projectId: 'smart-traffic-frontend',
    storageBucket: 'smart-traffic-frontend.firebasestorage.app',
    androidClientId: '820367744835-o240i46k2mfhccphrvo7bs85gcjsngkm.apps.googleusercontent.com',
    iosClientId: '820367744835-90urleu57pcjjm5sesl109p9k6k6chhj.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartTrafficFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZFK6n7A5Py1JcXKuHYghg-f9zIIS-B8c',
    appId: '1:820367744835:web:131e834c4d646eb90419f6',
    messagingSenderId: '820367744835',
    projectId: 'smart-traffic-frontend',
    authDomain: 'smart-traffic-frontend.firebaseapp.com',
    storageBucket: 'smart-traffic-frontend.firebasestorage.app',
    measurementId: 'G-61Y983PKP4',
  );

}